### ISSUE TITLE
Private pods source

### ISSUE THREAD

**Issue by JanC** [blakgeek/cordova-plugin-cocoapods-support#26]
Hi,
is there a way to add the `source` parameter to the Podfile so that I can use also private pods

The generated Podfile  would then looks like this
```
# Podfile
platform :ios, '8.0'
use_frameworks!

source 'git@github.com:foo/bar-cocoapods-specs.git'

pod 'MyKit', '~> 3.2'
```

cheers

**Comment by meewii** [comment]
+1

**Comment by samgabriel** [comment]
+1

**Comment by gotoAndBliss** [comment]
+1

**Comment by ach** [comment]
+1, please merge this

**Comment by JanC** [comment]
Hi, this issue is closed but the pull request is still open ..

**Comment by blakgeek** [comment]
The functionality was added but not using the same implementation.

On Feb 9, 2017 7:48 AM, "Jan Chaloupecky" <notifications@github.com> wrote:

Hi, this issue is closed but the pull request is still open ..

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/blakgeek/cordova-plugin-cocoapods-support/issues/26#issuecomment-278631409>,
or mute the thread

**Comment by ach** [comment]
Just noticed: 1.2.20 is updated here, but not released on npm. I need to use git-repo of plugin to get it work.

**Comment by blakgeek** [comment]
Oops.  It's published now.
